In [53]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from   sklearn.linear_model import LogisticRegression
from   sklearn.preprocessing import MinMaxScaler, LabelEncoder
from   sklearn.model_selection import train_test_split
from   sklearn.metrics import confusion_matrix, accuracy_score

## Problem 1

The file caesarian data.txt contains 80 records; each record lists 5 features used by a doctor to
determine whether or not to recommend that a baby be delivered by Caesarian section


- **age**: patient’s age in years;
- **num**: number of previous deliveries by patient;
- **tim**: delivery date (0=timely, 1 = premature, 2 = late);
- **pre**: blood pressure (0=low, 1=normal, 2=high);
- **hrt**: heart (0=healthy, 1=unhealthy);
- **cae**: decision (0=normal delivery, 1=use Caesarian);

Use features “age”, “num”, and “hrt” to perform the following tasks:

#### (a) Perform the Logistic Regression (note normalize data first). What are the learned model parameters?

In [8]:
data = pd.read_csv("./caesarian_data.txt", 
                   delimiter=" ", 
                   header=None,
                   names=["age", "num", "tim", "pre", "hrt", "cae"])
data.head()

age  num  tim  pre  hrt  cae
0   22    1    0    2    0    0
1   26    2    0    1    0    1
2   26    2    1    1    0    0
3   28    1    0    2    0    0
4   22    2    0    1    0    1

In [9]:
data.describe()

age        num        tim        pre        hrt        cae
count  80.000000  80.000000  80.000000  80.000000  80.000000  80.000000
mean   27.687500   1.662500   0.637500   1.000000   0.375000   0.575000
std     5.017927   0.794662   0.815107   0.711568   0.487177   0.497462
min    17.000000   1.000000   0.000000   0.000000   0.000000   0.000000
25%    25.000000   1.000000   0.000000   0.750000   0.000000   0.000000
50%    27.000000   1.000000   0.000000   1.000000   0.000000   1.000000
75%    32.000000   2.000000   1.000000   1.250000   1.000000   1.000000
max    40.000000   4.000000   2.000000   2.000000   1.000000   1.000000

In [18]:
# Select the features that the problem specified
features = data[["age", "num", "hrt"]]
features.head(5)

age  num  hrt
0   22    1    0
1   26    2    0
2   26    2    0
3   28    1    0
4   22    2    0

In [23]:
# Normalizing data using MinMax
scaler = MinMaxScaler().fit(features)
X = scaler.transform(features)
y = data["cae"].to_numpy()

print(f"Example head of features matrix X: \n{X[:5]}\n")
print(f"Example head of labels vector y: \n{y[:5]}")

Example head of features matrix X: 
[[0.2173913  0.         0.        ]
 [0.39130435 0.33333333 0.        ]
 [0.39130435 0.33333333 0.        ]
 [0.47826087 0.         0.        ]
 [0.2173913  0.33333333 0.        ]]

Example head of labels vector y: 
[0 1 0 0 1]


In [25]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)
model = LogisticRegression()
model.fit(x_train, y_train)
a = model.coef_
b = model.intercept_

print("trained model parameters are:")
print(a, b)

trained model parameters are:
[[0.04524739 0.13766913 1.13222396]] [-0.18050479]


#### (b) Evaluate the performance of your Logistic Regression classifier by using the metrics discussed in class.

In [44]:
y_predict       = model.predict(x_train)
y_predict_prob  = model.predict_proba(x_train)

print(f"Printing first few:")
print(f"Actual class\tPredicted class\t\tPredicted probabilities")
for n in range(0, 10):
    print(f"{y_train[n]}\t\t{y_predict[n]}\t\t\t{y_predict_prob[n]}")

Printing first few:
Actual class	Predicted class		Predicted probabilities
0		1			[0.25483151 0.74516849]
1		0			[0.54402823 0.45597177]
0		0			[0.52968426 0.47031574]
1		1			[0.27460314 0.72539686]
1		0			[0.54012155 0.45987845]
0		1			[0.27303843 0.72696157]
0		0			[0.54061017 0.45938983]
1		1			[0.26364321 0.73635679]
1		0			[0.52919415 0.47080585]
1		0			[0.52625231 0.47374769]


In [45]:
ypred_train        = model.predict(x_train)
accuracy_train     = accuracy_score(ypred_train, y_train)
conf_matrix_train  = confusion_matrix(ypred_train, y_train)
print('Accuracy for training data (R^2): ', accuracy_train, '\n')
print('Confusion matrix for training data:\n', conf_matrix_train, '\n')

ypred_test         = model.predict(x_test)
accuracy_test      = accuracy_score(y_test,ypred_test)
conf_matrix_test   = confusion_matrix(y_test, ypred_test)
print('Accuracy for test data (R^2): ', accuracy_test, '\n')
print('Confusion matrix for test data:\n', conf_matrix_test, '\n')

Accuracy for training data (R^2):  0.640625 

Confusion matrix for training data:
 [[23 18]
 [ 5 18]] 

Accuracy for test data (R^2):  0.6875 

Confusion matrix for test data:
 [[5 1]
 [4 6]] 



pretty bad ...

#### (c) How does the hyperparameter of l2 penalty affect the performance of your classifier?

#### (d) What is the threshold used in logistic regression? How does the model perform if we set the threshold of estimated probability to 0.6 in part (a) for Caesarian?

## Problem 2. 

The file iris.csv contains the data for three different species of iris flowers. Use features “petal length” and “petal width” to perform the following tasks

In [49]:
iris = pd.read_csv("./iris.csv")
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [65]:
features = iris[["petal_length", "petal_width"]]
scaler = MinMaxScaler().fit(features)
X = scaler.transform(features)
y = iris[["species"]].to_numpy().ravel()
y1 = iris[["species"]].to_numpy()


print(f"Example head of features matrix X: \n{X[:5]}\n")
print(f"Example head of labels vector y  (we need to use this): \n{y[:5]}\n")
print(f"Example head of labels vector y1 (As opposed to this): \n{y1[:5]}")

Example head of features matrix X: 
[[0.06779661 0.04166667]
 [0.06779661 0.04166667]
 [0.05084746 0.04166667]
 [0.08474576 0.04166667]
 [0.06779661 0.04166667]]

Example head of labels vector y  (we need to use this): 
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']

Example head of labels vector y1 (As opposed to this): 
[['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']]


In [63]:
# Encode the target labels
labelEncoder = LabelEncoder()
y_encoded = labelEncoder.fit_transform(y)
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### (a) Use the one-versus-the-rest strategy to classify the iris flowers. Evaluate the performance of your classifier.

#### (b) Use the softmax regression to classify the iris flowers. Evaluate the performance of your classifier.

#### (c) Compare and Discuss your results.